services:
  mysql:
    image: mysql:8.0
    container_name: mysql_jira
    restart: always
    environment:
      MYSQL_DATABASE: springboot_base_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jira-network

volumes:
  mysql_data:

networks:
  jira-network:
    driver: bridge