services:
  mysql:
    image: mysql:8.0
    container_name: mysql_jira
    restart: always
    environment:
      MYSQL_DATABASE: springboot_base_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jira-network
  redis_jira:
    image: redis:7.2-alpine
    container_name: redis_jira
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis_data:/data
    restart: always
    networks:
      - jira-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_NODE_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jira-network
volumes:
  mysql_data:
  rabbitmq_data:
networks:
  jira-network:
    driver: bridge