spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3307/springboot_base_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        pool-name: Primary-Hikari-Pool
    replica:
      jdbc-url: jdbc:mysql://localhost:3307/springboot_base_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        pool-name: Replica-Hikari-Pool
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
      default_batch_fetch_size: ${DEFAULT_BATCH_FETCH_SIZE:50}
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      sentinel:
#        master: your_master_name
#        nodes:
#          - ip1:port1 # IP and Port Sentinel 1
#          - ip2:port2 # Sentinel 2
#          - ip3:port3 # Sentinel 3
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
logging:
  level:
    com.congpv.springboot_base_project: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb.core: INFO
    com.zaxxer.hikari: INFO
    org.springframework.security: DEBUG