spring:
  application:
    name: springboot-base-project
  
  profiles:
    active: dev

dotenv:
  enabled: true

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION}

sentry:
  dsn: ${SENTRY_DSN}
  logging:
    mdc-tags: "traceId"