server:
  port: 8080

spring:
  application:
    name: springboot-base-project

  # ===== Datasource Configuration =====
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_base_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  # ===== JPA / Hibernate Configuration =====
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# ===== Logging =====
logging:
  level:
    root: INFO
    com.congpv.springboot_base_project: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ===== App specific configs =====
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000
