ALTER TABLE tasks
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE tasks
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE projects
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE projects
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE comments
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE comments
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE log_times
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE log_times
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE project_members
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE project_members
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

ALTER TABLE users
    ADD COLUMN created_by VARCHAR(50) DEFAULT 'SYSTEM';
ALTER TABLE users
    ADD COLUMN updated_by VARCHAR(50) DEFAULT 'SYSTEM';

